Fail on error, some message tweaks.
Closes #2.

diff --git a/bin/spam b/bin/spam
--- a/bin/spam
+++ b/bin/spam
@@ -2,6 +2,9 @@
 #
 # Scaled Package Manager bootstrap script
 
+# oh bash, why isn't this the default?
+set -e
+
 # determine the location where pacman will store its bits
 if [ -z "$SCALED_HOME" ]; then
     SCALED_HOME=$HOME/.scaled
@@ -21,8 +24,8 @@ else
    THIS_SPAM=$0
 fi
 if [ -x "$PACMAN_SPAM" -a "$PACMAN_SPAM" != "$THIS_SPAM" ]; then
-    echo "Reexecing via '$PACMAN_SPAM'"
-    echo "You may wish to replace '$THIS_SPAM' with a symlink to the above."
+    echo "[Reexecing via '$PACMAN_SPAM']"
+    echo "[You may wish to replace '$THIS_SPAM' with a symlink to the above.]"
     exec "$PACMAN_SPAM" "$@"
 fi
 
@@ -31,14 +34,14 @@ download() {
   local URL="$1"
   local FILE="$2"
 
-  echo "Downloading $URL..."
+  echo "[Downloading $URL...]"
   mkdir -p "${FILE%/*}" && {
       if hash curl 2>/dev/null; then
           curl -L -s -S -o "$FILE" $URL
       elif hash wget 2>/dev/null; then
           wget -nv -O "$FILE" $URL
       else
-          echo "Need curl or wget to install dependencies."
+          echo "*** Error: 'curl' or 'wget' required to install dependencies."
           exit 255
       fi
   } && [[ -s "$FILE" ]]
@@ -54,10 +57,10 @@ fi
 declare PACMAN_GIT=https://github.com/scaled/pacman.git
 if [ ! -d "$PACMAN_ROOT" ]; then
     if hash git 2>/dev/null; then
-        echo "Cloning $PACMAN_GIT..."
+        echo "[Cloning $PACMAN_GIT...]"
         git clone -q "$PACMAN_GIT" "$PACMAN_ROOT" && [[ -d "$PACMAN_ROOT" ]]
     else
-        echo "Need 'git' to install dependencies."
+        echo "*** Error: 'git' required to install dependencies."
         exit 255
     fi
 fi
@@ -70,15 +73,15 @@ if [ ! -s "$PACMAN_JAR" ]; then
     declare JAVAC_CMD=javac
     [[ -e "$JAVA_HOME/bin/javac" ]] && JAVA_CMD="$JAVA_HOME/bin/javac"
 
-    pushd "$PACMAN_ROOT"
+    pushd "$PACMAN_ROOT" >/dev/null
     rm -rf target/classes
     mkdir -p target/classes
     find src/main/java -name '*.java' > target/pacman.sources
-    echo "Compiling Scaled package manager..."
+    echo "[Compiling Scaled package manager...]"
     $JAVAC_CMD -classpath "$M2MFETCHER" -d target/classes @target/pacman.sources
     cd target/classes
     jar -cf ../module.jar .
-    popd
+    popd >/dev/null
 fi
 
 addJvmArg () {
